name: Lean_x86_64

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 检查
      uses: actions/checkout@main

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

    - name: 下载源代码
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: |
        rm -rf ./openwrt
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        
    - name: 预处理feeds
      working-directory: ./openwrt
      run: |
        echo "src-git helloworld https://github.com/fw876/helloworld.git" >> ./feeds.conf.default
        echo "src-git openclash https://github.com/vernesong/OpenClash;master" >> ./feeds.conf.default
        mkdir package/openwrt-packages && git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git ./package/openwrt-packages/luci-theme-argon

    - name: 更新feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 自定义设置
      working-directory: ./openwrt
      run: |
        sed -i 's/192.168.1.1/10.0.0.1/g' package/base-files/files/bin/config_generate
    
    - name: 处理编译配置
      run: |
        cp config.default ./openwrt/.config
        
    - name: 下载包文件
      working-directory: ./openwrt
      run: |
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译固件
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name : 上传固件与目录
      uses: actions/upload-artifact@main
      with:
        name: Lean
        path: openwrt/bin
